### PR TITLE
Fix the 'memfs' example to pass the tests

### LINKED ISSUE #16: Open read-only file with FILE_FLAG_DELETE_ON_CLOSE flag
**Test**
There are two lines of command for [winfstest](https://github.com/Liryna/winfstest)

`expect("CreateFile %s GENERIC_WRITE 0 0 CREATE_ALWAYS FILE_ATTRIBUTE_READONLY 0" % name, 0)`
`expect("CreateFile %s GENERIC_WRITE 0 0 OPEN_EXISTING FILE_FLAG_DELETE_ON_CLOSE 0" % name, "ERROR_ACCESS_DENIED")`

**Environment 1:**
1. Installed Dokany v2.2.0.1000
2. Run - `.\memfs.exe /d /l M:`
3. Run test

Log:
```
###Create file handle = 0x0000023729EAA7A0, eventID = 0005, event Info = 0x0000023729E61D30
Dokan Information: DokanEndDispatchCreate() status = 0, file handle = 0x0000023729EAA7A0, eventID = 0005, result = 0x2
Dokan Information: SendAndPullEventInformation() with NTSTATUS 0x0, context 0x29eaa7a0, and result object 0x0000023729F1B790 with size 48
...
###Cleanup file handle = 0x0000023729EAA7A0, eventID = 0005, event Info = 0x0000023729E61D30
Dokan Information: SendAndPullEventInformation() with NTSTATUS 0x0, context 0x29eaa7a0, and result object 0x0000023729F1B790 with size 48
###Close file handle = 0x0000023729EAA7A0, eventID = 0005, event Info = 0x0000023729E61D30
###Create file handle = 0x0000023729EAA7A0, eventID = 0006, event Info = 0x0000023729E61D30
Dokan Information: DokanEndDispatchCreate() status = c0000121, file handle = 0x0000000000000000, eventID = -001, result = 0x5
Dokan Information: SendAndPullEventInformation() with NTSTATUS 0xc0000121, context 0x0, and result object 0x0000023729F1B790 with size 48
``` 
Tests passed correctly. The result is expected:
**Dokan Information: DokanEndDispatchCreate() status = c0000121, file handle = 0x0000000000000000, eventID = -001, result = 0x5**

**Environment 2:**
1. Clone the current repository from the master branch. Dokany version is 2.2.0.1000.
2. Build and run the 'memfs' example
3. Run test

Log:
```
###Create file handle = 0x000002450658DB00, eventID = 0005, event Info = 0x00000245064E9900
Dokan Information: DokanEndDispatchCreate() status = 0, file handle = 0x000002450658DB00, eventID = 0005, result = 0x2
Dokan Information: SendAndPullEventInformation() with NTSTATUS 0x0, context 0x658db00, and result object 0x0000024508141FF0 with size 48
...
###Cleanup file handle = 0x000002450658DB00, eventID = 0005, event Info = 0x00000245064E9900
Dokan Information: SendAndPullEventInformation() with NTSTATUS 0x0, context 0x658db00, and result object 0x0000024508141FF0 with size 48
###Close file handle = 0x000002450658DB00, eventID = 0005, event Info = 0x00000245064E9900
###Create file handle = 0x000002450658DB00, eventID = 0006, event Info = 0x00000245064E9900
Delete failed, ask parent folder if we have the right
Parent give us the right to delete
Dokan Information: DokanEndDispatchCreate() status = 0, file handle = 0x000002450658DB00, eventID = 0006, result = 0x1
Dokan Information: SendAndPullEventInformation() with NTSTATUS 0x0, context 0x658db00, and result object 0x0000024508141FF0 with size 48
< crash >
``` 
The program crashes after this operation:
**Dokan Information: DokanEndDispatchCreate() status = 0, file handle = 0x000002450658DB00, eventID = 0006, result = 0x1**

### PR DESCRIPTION
**Pull request by denisovpi**
Fix #16

Also, see [discussion](https://github.com/dokan-dev/dokany/issues/1255)

### CODE REVIEW

File: dokan/examples/memfs/main.rs [hunk 1]
```diff
@@ -499,14 +496,25 @@ impl<'c, 'h: 'c> FileSystemHandler<'c, 'h> for MemFsHandler {
 		let delete_on_close = create_options & FILE_DELETE_ON_CLOSE > 0;
 		let path_info = path::split_path(&self.root, file_name)?;
 		if let Some((name, parent)) = path_info {
+			if create_options & FILE_DIRECTORY_FILE > 0 {
+				if let Some(stream_info) = &name.stream_info {
+					if !stream_info.check_default(true)? {
```
Comment (Liryna) [inline dokan/examples/memfs/main.rs:501]: There is no other cleaner way to know if this is a file ?

File: dokan/examples/memfs/main.rs [hunk 2]
```diff
@@ -499,14 +496,25 @@ impl<'c, 'h: 'c> FileSystemHandler<'c, 'h> for MemFsHandler {
...
+						Err(STATUS_NOT_A_DIRECTORY)?;
```
Comment (Liryna) [inline dokan/examples/memfs/main.rs]: Should this return ?

File: dokan/examples/memfs/main.rs (hunk 1 above)
Comment (denisovpi) [reply dokan/examples/memfs/main.rs:501]: This is a check to see if an entry (file/directory) has streams. I think it was the code author's decision on how to handle streams.

File: dokan/examples/memfs/main.rs (hunk 2 above)
Comment (denisovpi) [reply dokan/examples/memfs/main.rs]: Yes, we should return an error if the directory has streams (except for the default stream ':$I30:$INDEX_ALLOCATION'). I could insert this check elsewhere (for exp, line 532), but then it would have to be inserted in multiple places, for different operations (CreateDirectory, RemoveDirectory, etc)

Comment (Liryna) [reply dokan/examples/memfs/main.rs]: Sorry I meant that I believe `return` is missing before `Err(STATUS_NOT_A_DIRECTORY)?;` ?

Comment (denisovpi) [reply dokan/examples/memfs/main.rs]: Ah, I see. In Rust, the expressions `return Err(...);` and `Err(...)?;` are equivalent. I didn't see in the Rust guidelines which option is recommended to use. I've seen both usages in other rust projects. Overall you are right, I will change this to make the code more consistent.

**Comment by Liryna** [comment]
Thanks @denisovpi for the investigation and providing a fix! Very appreciated 🏆
